.TH DKIM-MILTER 8 2023-12-27 "DKIM Milter 0.1.0"
.SH NAME
dkim-milter \- milter for DKIM signing and verification
.SH SYNOPSIS
.SY dkim-milter
.OP \-c path
.OP \-L level
.OP \-l target
.OP \-n
.OP \-p socket
.OP \-s name
.YS
.SH DESCRIPTION
.B dkim-milter
is a milter application that signs and verifies messages using the
.I DomainKeys Identified Mail
protocol (RFC\~6376).
.PP
The
.B dkim-milter
program reads configuration parameters from file
.I /etc/dkim-milter/dkim-milter.conf
at startup.
The default location of the configuration file may be overridden using the
.B \-\-config-file
option.
Command-line options take precedence over the corresponding parameters in the
configuration file.
Setting parameters in the configuration file is generally preferred over using
the command-line options.
.PP
Invoking
.B dkim-milter
starts the milter in the foreground.
While it is running, the milter will process connections from the MTA according
to the configuration settings.
The milter can be shut down by sending it a termination signal.
.SH OPTIONS
.TP
.BR \-c " \fIpath\fR, " \-\-config-file " \fIpath\fR"
Path to configuration file.
See
.BR dkim-milter.conf (5)
for the reference documentation for DKIM Milter configuration files.
If this option is not used, configuration parameters are read from the default
configuration file
.IR /etc/dkim-milter/dkim-milter.conf .
.TP
.BR \-n ", " \-\-dry-run
Process messages normally, but do not take action or apply modifications.
.TP
.BR \-h ", " \-\-help
Print usage information.
.TP
.BR \-l " \fItarget\fR, " \-\-log-destination " \fItarget\fR"
Destination for log messages.
Supported destinations are
.BR syslog ,
to write log messages to the system logger, and
.BR stderr ,
to write log messages to standard error.
.TP
.BR \-L " \fIlevel\fR, " \-\-log-level " \fIlevel\fR"
Minimum severity of messages to log.
The supported log levels are
.BR error ,
.BR warn ,
.BR info ,
and
.BR debug .
.TP
.BR \-p " \fIsocket\fR, " \-\-socket " \fIsocket\fR"
Listening socket of the milter.
The given socket specification string describes the socket that the milter
should open for the connection from the MTA.
See
.BR dkim-milter.conf (5)
for a description of the format.
.TP
.BR \-s " \fIname\fR, " \-\-syslog-facility " \fIname\fR"
Facility to use for syslog messages.
Acceptable names are those defined by syslog (in lower case minus the
.B LOG_
prefix).
.TP
.BR \-V ", " \-\-version
Print version information.
.SH FILES
.I /etc/dkim-milter/dkim-milter.conf
.SH SEE ALSO
.BR dkim-milter.conf (5)
